### ISSUE TITLE
Clean Version

### ISSUE THREAD

**Issue by DeinoRaptor** [Leurak/TrollRAT#18]
Is there a Clean Version

**Comment by Nikitaw99** [comment]
> A remote trolling software mainly intended for Tech Support Scammers. 

> remote

that's the first thing i want to mention here, this is supposed to be used to harass *another* pc.

second of all, if you want to see how it works in action, watch this; https://www.youtube.com/watch?v=wv12fhgugz4

that's how "clean" it gets
