### ISSUE TITLE
Screen display

### ISSUE THREAD

**Issue by LoganDark** [Leurak/TrollRAT#19]
It would be cool to be able to watch what's happening on the screen, maybe even hear what the microphone picks up or watch what the webcam captures. It would be displayed in like a little picture-in-picture thing on the bottom right corner of the web gui.

**Comment by Leurak** [comment]
You can already do screenshots. Video stuff isn't planned, as TrollRAT is intended to run on a VM on your main or a nearby computer to troll scammers, so you can just see the screen anyway.
