### ISSUE TITLE
Feature Request: Make it possible to remotely control mouse/keyboard input

### ISSUE THREAD

**Issue by Derpitron** [Leurak/TrollRAT#27]
I don't know how feasible it would be to implement, but it seems fun for trolling purposes.

**Comment by LoganDark** [comment]
The goal of this project is to be troll-y, but _not in a way that could be to do anything malicious_. Full control of someone's computer can definitely be used maliciously, which is why this doesn't allow that.

> TrollRAT is not made for data stealing, full control or other bad things.

**Comment by Derpitron** [comment]
If the RAT shouldn't be used maliciously, then why is there a process killer, with a Crash Windows option? That seems like something that could at the very least corrupt data, right?

**Comment by LoganDark** [comment]
"Some of this tool can be used maliciously, so why not make it more malicious?"

Because being malicious is not the goal.

It's for trolling. Trolling can be malicious but that's still not the goal of the program.
